package com.itant.autoclick.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.itant.autoclick.model.GuanKaPoint;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GUAN_KA_POINT".
*/
public class GuanKaPointDao extends AbstractDao<GuanKaPoint, Long> {

    public static final String TABLENAME = "GUAN_KA_POINT";

    /**
     * Properties of entity GuanKaPoint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property X = new Property(1, int.class, "x", false, "X");
        public final static Property Y = new Property(2, int.class, "y", false, "Y");
        public final static Property Color = new Property(3, String.class, "color", false, "COLOR");
    }


    public GuanKaPointDao(DaoConfig config) {
        super(config);
    }
    
    public GuanKaPointDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GUAN_KA_POINT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"X\" INTEGER NOT NULL ," + // 1: x
                "\"Y\" INTEGER NOT NULL ," + // 2: y
                "\"COLOR\" TEXT);"); // 3: color
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GUAN_KA_POINT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GuanKaPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getX());
        stmt.bindLong(3, entity.getY());
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(4, color);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GuanKaPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getX());
        stmt.bindLong(3, entity.getY());
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(4, color);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GuanKaPoint readEntity(Cursor cursor, int offset) {
        GuanKaPoint entity = new GuanKaPoint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // x
            cursor.getInt(offset + 2), // y
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // color
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GuanKaPoint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setX(cursor.getInt(offset + 1));
        entity.setY(cursor.getInt(offset + 2));
        entity.setColor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GuanKaPoint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GuanKaPoint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GuanKaPoint entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
